using System;
using System.Collections.Generic;

namespace LimpiezaProyect.Models
{
    public partial class PurchLine
    {
        public string Purchid { get; set; } = null!;
        public string Itemid { get; set; } = null!;
        public int Purchstatus { get; set; }
        public DateTime Shippingdaterequested { get; set; }
        public DateTime Deliverydate { get; set; }
        public string Name { get; set; } = null!;
        public string Taxgroup { get; set; } = null!;
        public decimal Qtyordered { get; set; }
        public decimal Purchreceivednow { get; set; }
        public decimal Remainpurchphysical { get; set; }
        public decimal Remainpurchfinancial { get; set; }
        public decimal Priceunit { get; set; }
        public decimal Purchprice { get; set; }
        public string Currencycode { get; set; } = null!;
        public decimal Linepercent { get; set; }
        public decimal Linedisc { get; set; }
        public decimal Lineamount { get; set; }
        public string Externalitemid { get; set; } = null!;
        public string Purchunit { get; set; } = null!;
        public DateTime Confirmeddlv { get; set; }
        public long Addressrefrecid { get; set; }
        public string Inventtransid { get; set; } = null!;
        public string Vendgroup { get; set; } = null!;
        public string Vendaccount { get; set; } = null!;
        public int Addressreftableid { get; set; }
        public decimal Purchqty { get; set; }
        public decimal Purchmarkup { get; set; }
        public decimal Inventreceivednow { get; set; }
        public decimal Multilndisc { get; set; }
        public decimal Multilnpercent { get; set; }
        public int Purchasetype { get; set; }
        public int Covref { get; set; }
        public decimal Remaininventphysical { get; set; }
        public string Taxitemgroup { get; set; } = null!;
        public string Transactioncode { get; set; } = null!;
        public DateTime Shippingdateconfirmed { get; set; }
        public string Countyorigdest { get; set; } = null!;
        public int Taxautogenerated { get; set; }
        public decimal Underdeliverypct { get; set; }
        public decimal Overdeliverypct { get; set; }
        public decimal Tax1099amount { get; set; }
        public string Barcode { get; set; } = null!;
        public string Barcodetype { get; set; } = null!;
        public string Inventrefid { get; set; } = null!;
        public string Inventreftransid { get; set; } = null!;
        public int Itemreftype { get; set; }
        public string Projtransid { get; set; } = null!;
        public int Blocked { get; set; }
        public int Complete { get; set; }
        public string Reqplanidsched { get; set; } = null!;
        public string Reqpoid { get; set; } = null!;
        public string Itemrouteid { get; set; } = null!;
        public string Itembomid { get; set; } = null!;
        public string Lineheader { get; set; } = null!;
        public int Scrap { get; set; }
        public string Returnactionid { get; set; } = null!;
        public int Intercompanyorigin { get; set; }
        public string Projcategoryid { get; set; } = null!;
        public string Projid { get; set; } = null!;
        public string Inventdimid { get; set; } = null!;
        public string Transport { get; set; } = null!;
        public string Statprocid { get; set; } = null!;
        public string Port { get; set; } = null!;
        public string Assetid { get; set; } = null!;
        public int Assettranstypepurch { get; set; }
        public string Assetbookid { get; set; } = null!;
        public string Projlinepropertyid { get; set; } = null!;
        public string Projtaxitemgroupid { get; set; } = null!;
        public string Projtaxgroupid { get; set; } = null!;
        public decimal Projsalesprice { get; set; }
        public string Projsalescurrencyid { get; set; } = null!;
        public string Intercompanyinventtransid { get; set; } = null!;
        public string Projsalesunitid { get; set; } = null!;
        public string Deliveryname { get; set; } = null!;
        public int Deliverytype { get; set; }
        public string Customerref { get; set; } = null!;
        public string Custpurchaseorderformnum { get; set; } = null!;
        public int Stattriangulardeal { get; set; }
        public string Tax1099state { get; set; } = null!;
        public decimal Tax1099stateamount { get; set; }
        public int Itemtagging { get; set; }
        public int Casetagging { get; set; }
        public int Pallettagging { get; set; }
        public decimal Remaininventfinancial { get; set; }
        public Guid Purchreqlinerefid { get; set; }
        public DateTime Depreciationstartdate { get; set; }
        public string Activitynumber { get; set; } = null!;
        public int Returnstatus { get; set; }
        public string Returndispositioncodeid { get; set; } = null!;
        public int Createfixedasset { get; set; }
        public string Assetgroup { get; set; } = null!;
        public string Reqattention { get; set; } = null!;
        public string Purchreqid { get; set; } = null!;
        public long Tax1099recid { get; set; }
        public int Matchingpolicy { get; set; }
        public long Procurementcategory { get; set; }
        public int Linedeliverytype { get; set; }
        public long Sourcedocumentline { get; set; }
        public long Defaultdimension { get; set; }
        public long Ledgerdimension { get; set; }
        public int Isdeleted { get; set; }
        public int Ismodified { get; set; }
        public long Matchingagreementline { get; set; }
        public long Manualentrychangepolicy { get; set; }
        public long Systementrychangepolicy { get; set; }
        public int Systementrysource { get; set; }
        public int Workflowstate { get; set; }
        public int Editableinworkflow { get; set; }
        public int Wfinvreceivedstate { get; set; }
        public int Wfdeliveryduestate { get; set; }
        public long Tax1099fields { get; set; }
        public int GsthsttaxtypeCa { get; set; }
        public long Deliverypostaladdress { get; set; }
        public long Linenumber { get; set; }
        public long TaxwithholditemgroupheadingTh { get; set; }
        public long Requester { get; set; }
        public long Accountingdistributiontemplate { get; set; }
        public int OperationtypeMx { get; set; }
        public int Stockedproduct { get; set; }
        public int Isfinalized { get; set; }
        public long Planreference { get; set; }
        public int Isinvoicematched { get; set; }
        public string Itempbaid { get; set; } = null!;
        public decimal TaxwithholdbasecurTh { get; set; }
        public string TaxwithholdgroupTh { get; set; } = null!;
        public string TaxservicecodeBr { get; set; } = null!;
        public DateTime IntrastatfulfillmentdateHu { get; set; }
        public long CfoptableBr { get; set; }
        public decimal StatisticvalueLt { get; set; }
        public string Psaretainscheduleid { get; set; } = null!;
        public decimal Psatotalretainamount { get; set; }
        public DateTime Servicedate { get; set; }
        public decimal Remainder { get; set; }
        public string Serviceaddress { get; set; } = null!;
        public decimal Inventinvoicenow { get; set; }
        public decimal Retaillinenumex1 { get; set; }
        public string Variantid { get; set; } = null!;
        public string Retailpackageid { get; set; } = null!;
        public decimal Rbopackagelinenum { get; set; }
        public decimal Retailtempvalueex2 { get; set; }
        public int Mcrdropshipment { get; set; }
        public string Mcrdropshipcomment { get; set; } = null!;
        public int Mcrdropshipstatus { get; set; }
        public int Agreementskipautolink { get; set; }
        public decimal Confirmedtaxamount { get; set; }
        public string Confirmedtaxwritecode { get; set; } = null!;
        public decimal Discamount { get; set; }
        public decimal Discpercent { get; set; }
        public int Ispwp { get; set; }
        public int Manualmodifiedfield { get; set; }
        public long Mcrorderline2pricehistoryref { get; set; }
        public string Pdscalculationid { get; set; } = null!;
        public decimal Pdscwinventreceivednow { get; set; }
        public decimal Pdscwqty { get; set; }
        public decimal Pdscwremaininventfinancial { get; set; }
        public decimal Pdscwremaininventphysical { get; set; }
        public long Projworker { get; set; }
        public long PurchcommitmentlinePsn { get; set; }
        public int Skipdistributionupdate { get; set; }
        public string Tamitemvendrebategroupid { get; set; } = null!;
        public DateTime Modifieddatetime { get; set; }
        public DateTime Createddatetime { get; set; }
        public string Dataareaid { get; set; } = null!;
        public int Recversion { get; set; }
        public long Partition { get; set; }
        public long Recid { get; set; }
        public decimal MntAdiccertificate { get; set; }
        public string MntCarriername { get; set; } = null!;
        public int MntPropertyid { get; set; }
        public string MntRouteid { get; set; } = null!;
        public string MntTankerid { get; set; } = null!;
        public decimal MntValuegp { get; set; }
        public decimal MntValueufc { get; set; }
        public int MntDeliverynumber { get; set; }
        public int MntDischargenumber { get; set; }
        public decimal Pqpreciocbt { get; set; }
        public decimal Pqprecioacuerdocomercial { get; set; }
        public long Pqrefrecidprecio { get; set; }
        public string Modifiedby { get; set; } = null!;
        public string Createdby { get; set; } = null!;
        public decimal Pqpreciotransportelc { get; set; }
        public decimal Purchprice1 { get; set; }
    }
}
